### ISSUE TITLE
Readme.md里增加Docker运行方式的说明

### ISSUE THREAD

**Issue by wizardbyron** [v55448330/lazy-balancer#1]

**Comment by v55448330** [comment]
因为启用了 iptables 控制，所以暂时不支持 docker 方式运行，如果需要使用 Docker，可以注释 iptables 相关代码

**Comment by mamacmm** [comment]
请问怎么注释掉 iptables 相关代码？
或者能否发布一个docker镜像，直接使用就可以了

**Comment by v55448330** [comment]
注释如下：
nginx/ip.py
line all

lazy_balancer/views.py
line 10: from nginx.ip import *
line 25: set_firewall()

proxy/views.py
line 11: from nginx.ip import *
line 227: set_firewall()

settings/views.py
line 7: from nginx.ip import set_firewall
line 61: set_firewall()

**Comment by v55448330** [comment]
我正在考虑将 iptables 控制取消掉，这样就可以跑在 docker 容器中了

**Comment by wizardbyron** [comment]
最主要还是django依赖的问题，解决这个问题django有点重。想想办法能不能换个轻量级的。

**Comment by v55448330** [comment]
@wizardbyron 其实 Django 已经很轻量了，主要是很方便的封装了很多实现，比如数据库，缓存，异步任务，配置，路由等。更关键的是有强大的扩展支持，依赖这个东西简单也复杂，各取所需；
后面需要想办法把部分依赖做成可插拔的方式实现就可以支持容器了。
另外这个项目诞生的时候定位的就是虚拟机、轻量级物理机平台（ATOM）等，通过这个项目，可以定制一些简单的物理负载均衡器，解决的是商用负载均衡器性价比和操作复杂的问题。
