### ISSUE TITLE
忘记密码

### ISSUE THREAD

**Issue by zhangyonghui9527** [v55448330/lazy-balancer#17]
我在登陆页面忘记了旧密码，请问我需要怎么做才能重置密码

**Comment by v55448330** [comment]
删除db.sqlite3，重新执行migration或者sqlite3删掉用户

**Comment by hale177** [comment]
docker 部署，按这个方式操作之后，重新创建管理员用户登录，映射得规则全没了啊  ？？

> 删除db.sqlite3，重新执行migration或者sqlite3删掉用户
