### ISSUE TITLE
支持HttpGuard以提供完善的安全服务

### ISSUE THREAD

**Issue by MoeMion** [v55448330/lazy-balancer#18]
开发者您好，
您的项目非常出色。
在生产和使用过程中高效的解决了问题。
这里提出一个小建议:
希望能增加[HttpGuard](https://github.com/centos-bz/HttpGuard)来提供Nginx安全防护，包括WAF和防CC。
感谢您的浏览，希望您能够采纳。

**Comment by v55448330** [comment]
看起来好像不太方便
1. 好像开源版停止维护了，只有商业版
2. 应该是基于 openresty 实现的，目前我这边是基于 tengine 模块实现的
