### ISSUE TITLE
Docker部署的情况下访问Post接口报错。

### ISSUE THREAD

**Issue by cmmi** [v55448330/lazy-balancer#19]
Docker部署后Get接口访问正常，Post接口访问报错
错误信息为 ：
400Undocumented | Error: Bad RequestResponse headers connection: keep-alive  content-length: 0  date: Thu, 02 Jan 2020 01:28:52 GMT  server: Tengine
以上错误信息为默认配置下产生。不知道是不是我配置有啥问题。

**Comment by cmmi** [comment]
补充一下
用Ubuntu重新部署下
发现是nginx的这一项配置的导致的
proxy_set_header  Connection  "upgrade";
上面那行配置信息注释掉之后，重新手动重载nginx配置就可以post数据。
我记得这个配置是给websocket协议用的。是否在普通http模式下应该将这行配置注释？

**Comment by v55448330** [comment]
我这里没有复现这个问题

**Comment by cmmi** [comment]
难道是特例？我部署了2次docker版本，一次克隆代码库主分支的版本，都是这样啊.....

**Comment by v55448330** [comment]
会不会跟你后端程序有关？你后端起一个 flask 的 hello world post 试试看，我之前有遇到因为 http header 不标准和 301 跨域导致的 post 提交失败，前者可以在主配置里打开“允许非标转发”，后者没办法，是浏览器限制

**Comment by cmmi** [comment]
未修改模板配置的情况
[http://nas.1sw.xyz:5000/4.0/index.php?share/file&user=admin&sid=yNCvpYaK](url)

修改模板配置后的情况
[http://nas.1sw.xyz:5000/4.0/index.php?share/file&user=admin&sid=yHAlhLGd](url)

其他的我无法提供更多了，我对pyhton不是很熟悉。后台是基于.net Core 3.1 + swager UI 来实现的。正常无代理和手动配置代理的情况下都可以正常访问。

**Comment by cmmi** [comment]
[原始配置模板下](http://nas.1sw.xyz:5000/4.0/index.php?share/file&user=admin&sid=yNCvpYaK)
[注释部分配置之后](http://nas.1sw.xyz:5000/4.0/index.php?share/file&user=admin&sid=yHAlhLGd)
后端使用.net core 3.1 + swagger UI 来实现的。在无代理和手动配置代理的情况下可以正常访问。
