### ISSUE TITLE
使用lazy-balancer 後端的伺服器只係記錄lazy-balancer 的IP

### ISSUE THREAD

**Issue by kklam201** [v55448330/lazy-balancer#27]
請問可以記錄原來的IP嗎?
使用lazy-balancer 後端的伺服器只係記錄lazy-balancer 的IP?
還有就是後端的網頁伺服器用使big5 的,如果使用預設的是utf8會變了亂碼,請問可以怎樣修改?

**Comment by v55448330** [comment]
自定义配置里面自己加header即可

**Comment by paraparak** [comment]
請問怎樣可以自定义配置,因為我是用docker 直接起動,之後我進入docker 後修改/etc/nginx/nginx.conf後,出去重啟之後又變回原來的設定了
如果方便可以提供一下設定的步驟或整個安裝的步驟嗎??
以下是部處lazy-balancer 的步驟你看看有沒有什麼問題


$ sudo yum install docker-ce
$ sudo docker pull v55448330/lazy-balancer:latest
$ sudo docker run -d --restart=always --net=host --name=lazy_balancer \
    -v /app/data/db:/app/lazy_balancer/db \
    -v /app/logs/nginx:/var/log/nginx \
    v55448330/lazy-balancer:latest


$ sudo docker exec lazy_balancer python manage.py makemigrations --noinput 2>/dev/null
$ sudo docker exec lazy_balancer python manage.py migrate --run-syncdb
