### ISSUE TITLE
http://127.0.0.1/req_status

### ISSUE THREAD

**Issue by Luolired** [v55448330/lazy-balancer#3]
File "/home/lizx/lazy-balancer-master/dashboard/views.py", line 26, in get_status_info
    'bytes_in' : r[2],
IndexError: list index out of range

/home/lizx/lazy-balancer-master# vi ./nginx/views.py
get_req_status()

http://127.0.0.1/req_status 不能访问,怎么处理

**Comment by Luolired** [comment]
用 /resource/nginx/nginx.template 替换配置问题解决

**Comment by v55448330** [comment]
你用的是 nginx 吧，这里用的是 tengine 的模块

**Comment by 371918642** [comment]
负载均衡随便新增一个节点，比如端口 34  ，保存提示保存失败，然后整站就打不开了

**Comment by v55448330** [comment]
Docker 版本提供已经编译好的
