### ISSUE TITLE
请求添加 ldap 用户接入支持 

### ISSUE THREAD

**Issue by hale177** [v55448330/lazy-balancer#46]
没想到项目23 年还在更新，给力啊！  之前的老版本用了 2 年多了，主要用来做测试环境的外网映射端口确实很不错 
日常使用就一个问题，希望能对接公司 ldap 用户，这样可以让其他用户登录进来自助添加端口映射和查询，
权限上可以保持和本地 admin一样的权限即可，不用做额外细化处理，这样就很完美了 

本来以为项目不更新了，希望作者大大有空能考虑下把接入 ldap 特性加进去 ：)

**Comment by v55448330** [comment]
这个可能比较难，多租户还涉及操作冲突，日志等等一系列问题，暂时没有精力设计这个
