### ISSUE TITLE
忘记密码，找回重建管理员后，映射规则全空了 

### ISSUE THREAD

**Issue by hale177** [v55448330/lazy-balancer#47]
docker 部署，按这个方式操作之后，重新创建管理员用户登录，映射得规则全没了啊  ？？

> 删除db.sqlite3，重新执行migration或者sqlite3删掉用户

_Originally posted by @hale177 in https://github.com/v55448330/lazy-balancer/issues/17#issuecomment-1874968168_

**Comment by v55448330** [comment]
当然，你可以从备份恢复，或者从其他节点同步
