### ISSUE TITLE
centos如何安装

### ISSUE THREAD

**Issue by baimoer** [v55448330/lazy-balancer#5]

**Comment by chengxingyao** [comment]
同问

**Comment by blueyan163** [comment]
同问

**Comment by v55448330** [comment]
并没有测试过，理论上是可以安装的

**Comment by jorgezx** [comment]
### 卸载nginx：
`yum remove -y nginx`
### 安装supervisor：
`yum install -y supervisor`
### 安装依赖：
> apt-get install   -->  yum install
### 启动supervisord：
```
systemctl enable supervisord
systemctl restart supervisord
```
centos7上亲测。

**Comment by one-two-my-gad** [comment]
centos7.5 安装成功后 为什么系统资源无法显示呢

**Comment by v55448330** [comment]
增加了 Docker 版本支持，直接用即可
